### ISSUE TITLE
How to check image orientation?

### ISSUE THREAD

**Issue by Hessel91** [Rebel59/oc-isogallery-plugin#3]
I would like to use your plugin in combination with masonry & lazyloading. 
for the masonry layout I would like to check if the image is orientated horizontal or vertical and then add a class to the image parent. 

First I did this with jquery, but I would like it to be executed before image loading. 
With the twig extension plugin installed is it possible to do something like this: ? 

 `<div class="{% if gallery.photos.getThumb(width) > gallery.photos.getThumb(height) %} vertical {% endif %}">`

**Comment by CptMeatball** [comment]
You can get the height and width properties from an image through the `height` and `width` properties of the image. 

So on the `photo` (File object) you can call `photo.width` and `photo.height`.

This should do it.

````twig
{% for photo in gallery.photos %}
  {% if photo.width > photo.height %}
    // landscape 
  {% else %}
    // portrait
  {% endif %}
{% endfor %}
````

**Comment by Hessel91** [comment]
Thank you for the fast support, this was what I was looking for =)
